version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: klinik_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - klinik
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_NAME: "Web Klinik Gigi"
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: klinik
      DB_USERNAME: root
      DB_PASSWORD: root

  nginx:
    image: nginx:alpine
    container_name: klinik_nginx
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - klinik

  mysql:
    image: mysql:8.0
    container_name: klinik_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: klinik
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - klinik

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: klinik_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - klinik

networks:
  klinik:
    driver: bridge

volumes:
  mysql_data:
